services:
  traefik:
    image: traefik:v3.0
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - "8090:8080"
      - "8081:8081"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml

  server:
    image: ghcr.io/aet-devops25/ticketing-service/server:latest
    build:
      context: ./server
      dockerfile: Dockerfile
      cache_from:
        - ghcr.io/aet-devops25/ticketing-service/server:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db
      - SPRING_DATASOURCE_USERNAME=spoved
      - SPRING_DATASOURCE_PASSWORD=secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.server-svc.loadbalancer.server.port=8080"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.routers.api.service=server-svc"
      - "traefik.http.routers.api.priority=100"
    restart: unless-stopped

  client:
    image: ghcr.io/aet-devops25/ticketing-service/client:latest
    build:
      context: ./client/frontend
      dockerfile: Dockerfile
      args:
        VITE_SERVER_API_URL: ${VITE_SERVER_API_URL:-http://${INSTANCE_IP}:8090/api/v1}
        VITE_AUTH_API_URL: ${VITE_AUTH_API_URL:-http://${INSTANCE_IP}:8090}
        VITE_GENAI_API_URL: ${VITE_GENAI_API_URL:-http://${INSTANCE_IP}:8000}
    environment:
      - VITE_SERVER_API_URL=${VITE_SERVER_API_URL:-http://${INSTANCE_IP}:8090/api/v1}
      - VITE_AUTH_API_URL=${VITE_AUTH_API_URL:-http://${INSTANCE_IP}:8090}
      - VITE_GENAI_API_URL=${VITE_GENAI_API_URL:-http://${INSTANCE_IP}:8000}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=PathPrefix(`/`) && !PathPrefix(`/api`) && !PathPrefix(`/auth`)"
      - "traefik.http.routers.client.entrypoints=web"
      - "traefik.http.routers.client.service=client-svc"
      - "traefik.http.routers.client.priority=100"
      - "traefik.http.services.client-svc.loadbalancer.server.port=3000"
    depends_on:
      - server
    restart: unless-stopped

  database:
    image: team-spoved-db
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=spoved
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=db
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  auth:
    image: auth-service
    build:
      context: ./auth
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db
      - SPRING_DATASOURCE_USERNAME=spoved
      - SPRING_DATASOURCE_PASSWORD=secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.auth-svc.loadbalancer.server.port=8030"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.routers.auth.service=auth-svc"
      - "traefik.http.routers.auth.priority=100"

  genai:
    image: genai-service
    build:
      context: ./genai
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - BACKEND_API_URL=http://${INSTANCE_IP}:8090/api/v1
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - server
    restart: unless-stopped

volumes:
  pgdata:
