services:

  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - --configFile=/etc/traefik/traefik.yml
    ports:
      - 8080:8080
      - 8089:8089
    volumes:
      - ./traefik/traefik.yml:/etc/traefik/traefik.yml
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - spoved-network

  ticket:
    image: ghcr.io/aet-devops25/ticketing-service/ticket:latest
    build:
      context: ./ticket
      dockerfile: Dockerfile
      cache_from:
        - ghcr.io/aet-devops25/ticketing-service/ticket:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db
      - SPRING_DATASOURCE_USERNAME=spoved
      - SPRING_DATASOURCE_PASSWORD=secret
      - USER_SERVICE_URL=http://user:8082/api/v1
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info

    labels:
      - "traefik.enable=true"
      - "traefik.http.services.ticket-svc.loadbalancer.server.port=8081"
      - "traefik.http.routers.ticket.rule=PathPrefix(`/api/v1/tickets`)"
      - "traefik.http.routers.ticket.entrypoints=web"
      - "traefik.http.routers.ticket.service=ticket-svc"
      - "traefik.http.routers.ticket.priority=100"
    depends_on:
      - database
      - user
    ports:
      - 8081:8081
    networks:
      - spoved-network
    restart: unless-stopped

  user:
    image: ghcr.io/aet-devops25/user-service/user:latest
    build:
      context: ./user
      dockerfile: Dockerfile
      cache_from:
        - ghcr.io/aet-devops25/user-service/user:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db
      - SPRING_DATASOURCE_USERNAME=spoved
      - SPRING_DATASOURCE_PASSWORD=secret
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.user-svc.loadbalancer.server.port=8082"
      - "traefik.http.routers.user.rule=PathPrefix(`/api/v1/users`)"
      - "traefik.http.routers.user.entrypoints=web"
      - "traefik.http.routers.user.service=user-svc"
      - "traefik.http.routers.user.priority=100"
    depends_on:
      - database
    ports:
      - 8082:8082
    networks:
      - spoved-network
    restart: unless-stopped

  media:
    image: ghcr.io/aet-devops25/media-service/media:latest
    build:
      context: ./media
      dockerfile: Dockerfile
      cache_from:
        - ghcr.io/aet-devops25/media-service/media:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db
      - SPRING_DATASOURCE_USERNAME=spoved
      - SPRING_DATASOURCE_PASSWORD=secret
      - MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE=health,info
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.media-svc.loadbalancer.server.port=8083"
      - "traefik.http.routers.media.rule=PathPrefix(`/api/v1/media`)"
      - "traefik.http.routers.media.entrypoints=web"
      - "traefik.http.routers.media.service=media-svc"
      - "traefik.http.routers.media.priority=100"
    depends_on:
      - database
    ports:
      - 8083:8083
    networks:
      - spoved-network
    restart: unless-stopped

  client:
    image: ghcr.io/aet-devops25/client-service/client:latest
    build:
      context: ./client/frontend
      dockerfile: Dockerfile
      args:
        VITE_TICKET_API_URL: http://localhost:8080/api/v1
        VITE_USER_API_URL: http://localhost:8080/api/v1
        VITE_MEDIA_API_URL: http://localhost:8080/api/v1
        VITE_AUTH_API_URL: http://localhost:8080
        VITE_GENAI_API_URL: http://localhost:8000

    environment:
      - VITE_TICKET_API_URL=http://localhost:8080/api/v1
      - VITE_USER_API_URL=http://localhost:8080/api/v1
      - VITE_MEDIA_API_URL=http://localhost:8080/api/v1
      - VITE_AUTH_API_URL=http://localhost:8080
      - VITE_GENAI_API_URL=http://localhost:8000

    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.client.rule=PathPrefix(`/`) && !PathPrefix(`/api`) && !PathPrefix(`/auth`)"
      - "traefik.http.routers.client.entrypoints=web"
      - "traefik.http.routers.client.service=client-svc"
      - "traefik.http.routers.client.priority=100"
      - "traefik.http.services.client-svc.loadbalancer.server.port=3000"
    depends_on:
      - traefik
      - ticket
      - user
      - media
      - auth
    networks:
      - spoved-network
    restart: unless-stopped

  database:
    image: team-spoved-db
    build:
      context: ./database
      dockerfile: Dockerfile
    environment:
      - POSTGRES_USER=spoved
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=db
    expose:
      - 5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - spoved-network
    restart: unless-stopped

  auth:
    image: auth-service
    build:
      context: ./auth
      dockerfile: Dockerfile
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/db
      - SPRING_DATASOURCE_USERNAME=spoved
      - SPRING_DATASOURCE_PASSWORD=secret
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.auth-svc.loadbalancer.server.port=8030"
      - "traefik.http.routers.auth.rule=PathPrefix(`/auth`)"
      - "traefik.http.routers.auth.entrypoints=web"
      - "traefik.http.routers.auth.service=auth-svc"
      - "traefik.http.routers.auth.priority=100"
    depends_on:
      - database
    ports:
      - 8030:8030
    networks:
      - spoved-network
    restart: unless-stopped

  genai:
    image: genai-service
    build:
      context: ./genai
      dockerfile: Dockerfile
      args:
        TICKET_API_URL: http://ticket:8081/api/v1
        USER_API_URL: http://user:8082/api/v1
        MEDIA_API_URL: http://media:8083/api/v1
        AUTH_API_URL: http://auth:8030
        GEMINI_API_KEY: ${GEMINI_API_KEY}
    
    environment:
      - TICKET_API_URL=http://ticket:8081/api/v1
      - USER_API_URL=http://user:8082/api/v1
      - MEDIA_API_URL=http://media:8083/api/v1
      - AUTH_API_URL=http://auth:8030
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - traefik
      - ticket
      - user
      - media
    ports:
      - 8000:8000
    networks:
      - spoved-network
    restart: unless-stopped

volumes:
  pgdata:

networks:
  spoved-network:
    driver: bridge