apiVersion: 1

alerting:
  alert_rules:
    - orgId: 1
      folderUID: ""           
      name: "spOveD VM alerts"
      interval: "1m"
      rules:
        - uid: vm_high_usage
          title: "VM Memory > 80%"
          condition: "A > 0.8 * total_memory_bytes"
          data:
            - refId: A
              datasourceUid: prom
              model:
                expr: sum(process_virtual_memory_bytes) by (instance)
              type: query
          for: "5m"
          labels:
            severity: critical
          annotations:
            summary: "High VM memory on {{ $labels.instance }}"