apiVersion: 1

groups:
  - orgId: 1
    name: spOveD_VM_alerts
    folder: "spOveD Alerts"
    interval: 60s

    rules:
      - uid: vm_high_usage
        title: High memmory usage
        condition: A
        data:
          - refId: A
            datasourceUid: prom
            queryType: instant
            relativeTimeRange:
              from: 300
              to:   0
            model:
              type: query
              datasource:
                type: prometheus
                uid: prom
              expr: |
                (
                  sum(process_virtual_memory_bytes) by (instance)
                  /
                  sum(node_memory_MemTotal_bytes) by (instance)
                )
                * 100 > 80
              intervalMs: 1000
              maxDataPoints: 43200

        for: 5m
        labels:
          severity: critical
        annotations:
          summary: High VM memory on {{ $labels.instance }}

      - uid: service_startup_slow
        title: Service startup duration over 30s
        condition: A
        data:
          - refId: A
            datasourceUid: prom
            queryType: instant
            relativeTimeRange:
              from: 300
              to:   0
            model:
              type: query
              datasource:
                type: prometheus
                uid: prom
              expr: |
                max by (service) (my_service_startup_seconds) > 30
              intervalMs: 1000
              maxDataPoints: 43200
        for: 5m
        labels:
          severity: warning
          service: "{{ $labels.service }}"
        annotations:
          summary: "Slow startup: {{ $labels.service }} took >30s"

      - uid: service_http_slow
        title: Duration of the HTTP requests longer than 2s
        condition: A
        data:
          - refId: A
            datasourceUid: prom
            queryType: instant
            relativeTimeRange:
              from: 300
              to:   0
            model:
              type: query
              datasource:
                type: prometheus
                uid: prom
              expr: |
                histogram_quantile(
                  0.95,
                  sum by (le,service) (
                    rate(http_request_duration_seconds_bucket[5m])
                  )
                ) > 2
              intervalMs: 1000
              maxDataPoints: 43200
        for: 5m
        labels:
          severity: critical
          service: "{{ $labels.service }}"
        annotations:
          summary: "Slow HTTP: 95th‑pct request for {{ $labels.service }} >2s"
