openapi: 3.0.3
info:
  title: GenAI Service API
  version: 1.0.0
  description: |
    Provides AI-powered endpoints for speech-to-text, text-to-speech, and conversational ticket generation.
    Integrates with Google Cloud and Gemini AI for advanced language and audio processing.
    Endpoints include speech recognition, AI-driven conversation, and audio synthesis.
    Metrics and health endpoints are exposed for monitoring.
paths:
  /speech-to-text:
    post:
      summary: Convert speech audio to text
      description: Converts uploaded audio (WAV or WebM) to text using Google Cloud Speech-to-Text.
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                audio:
                  type: string
                  format: binary
                  description: Audio file to transcribe (WAV or WebM)
      responses:
        '200':
          description: Successful transcription
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SpeechToTextResponse'
        '400':
          description: Invalid audio or no speech detected
        '500':
          description: Internal server error
  /query-ai:
    post:
      summary: Query Gemini AI for conversational response
      description: Generates a conversational response based on user input and conversation history.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/QueryAIRequest'
      responses:
        '200':
          description: AI response generated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/QueryAIResponse'
        '500':
          description: Internal server error
  /text-to-speech:
    post:
      summary: Convert text to speech
      description: Converts input text to speech audio using Google Cloud Text-to-Speech.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextToSpeechRequest'
      responses:
        '200':
          description: Audio file generated
          content:
            audio/wav:
              schema:
                type: string
                format: binary
        '500':
          description: Internal server error
components:
  schemas:
    SpeechToTextResponse:
      type: object
      properties:
        transcript:
          type: string
          description: The transcribed text from the audio
    QueryAIRequest:
      type: object
      properties:
        prompt:
          type: string
          description: The user input prompt
        conversation_historic:
          type: string
          description: The conversation history so far
    QueryAIResponse:
      type: object
      properties:
        response:
          type: string
          description: The AI-generated response
        updatedHistory:
          type: string
          description: The updated conversation history
    TextToSpeechRequest:
      type: object
      properties:
        text:
          type: string
          description: The text to convert to speech
