apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ticket-service-monitor
  namespace: monitoring
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: ticket-selector
  namespaceSelector:
    matchNames:
      - spoved
  endpoints:
    - port: {{ .Values.ticket.service.port }}
      path: /actuator/prometheus
      interval: 15s
