metadata:
  name: user-service-monitor
spec:
  selector:
    matchLabels:
      app: spoved-user-selector
  endpoints:
    - port: {{ .Values.user.service.port }}
      path: /actuator/prometheus
      interval: 15s
