global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'server'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['server:8080']

  - job_name: 'auth'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['auth:8030']

  - job_name: 'genai'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['genai:8000']