openapi: 3.0.3
info:
  title: Media Service API
  version: 1.0.0
  description: |
    Manages media files (photos, videos, audio) associated with tickets.
    Provides endpoints to upload, retrieve, and update analysis results and reasons for media items.
    Supports marking media as analyzed and storing AI-generated results.
    Metrics and health endpoints are exposed for monitoring.
paths:
  /media/{mediaId}:
    get:
      summary: Get media analysis data
      description: Retrieve analysis data for a specific media item by ID.
      parameters:
        - in: path
          name: mediaId
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Media analysis data
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaAnalysis'
        '404':
          description: Media not found
  /media/{mediaId}/analyzed:
    put:
      summary: Update analyzed status
      description: Mark a media item as analyzed or not.
      parameters:
        - in: path
          name: mediaId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                analyzed:
                  type: boolean
      responses:
        '200':
          description: Analyzed status updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaAnalysis'
        '404':
          description: Media not found
  /media/{mediaId}/result:
    put:
      summary: Update analysis result
      description: Update the AI-generated result for a media item.
      parameters:
        - in: path
          name: mediaId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                result:
                  type: string
      responses:
        '200':
          description: Analysis result updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaAnalysis'
        '404':
          description: Media not found
  /media/{mediaId}/reason:
    put:
      summary: Update analysis reason
      description: Update the reason for the analysis result of a media item.
      parameters:
        - in: path
          name: mediaId
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                reason:
                  type: string
      responses:
        '200':
          description: Analysis reason updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaAnalysis'
        '404':
          description: Media not found
components:
  schemas:
    MediaAnalysis:
      type: object
      properties:
        mediaId:
          type: integer
        analyzed:
          type: boolean
        result:
          type: string
        reason:
          type: string
        url:
          type: string
          description: URL to the media file
