api:
  dashboard: true
  insecure: true

log:
  level: DEBUG

entryPoints:
  web:
    address: ":8080" # app
  traefik:
    address: ":8089" # dashboard

providers:
  docker:
    exposedByDefault: false