apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: {{ .Values.namespace.name | default "spoved" }}
spec:
  selector:
    app: spoved-auth-selector
  ports:
    - port: {{ .Values.auth.service.port }}
      targetPort: {{ .Values.auth.service.targetPort }}
      protocol: TCP
  type: {{ .Values.auth.service.type }}
