apiVersion: apps/v1
kind: Deployment
metadata:
  name: spoved-auth
  namespace: {{ .Values.namespace.name | default "spoved" }}
spec:
  replicas: {{ .Values.auth.replicaCount }}
  selector:
    matchLabels:
      app: spoved-auth-selector
  template:
    metadata:
      labels:
        app: spoved-auth-selector
    spec:
      containers:
        - name: auth
          image: "{{ .Values.auth.image.repository }}:{{ .Values.auth.image.tag }}"
          imagePullPolicy: {{ .Values.auth.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.auth.service.targetPort }}
          env:
            {{- range .Values.auth.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}

