apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
  namespace: {{ .Values.namespace.name | default "spoved" }}
spec:
  replicas: {{ .Values.client.replicaCount }}
  selector:
    matchLabels:
      app: spoved-client-selector
  template:
    metadata:
      labels:
        app: spoved-client-selector
    spec:
      containers:
        - name: client
          image: "{{ .Values.client.image.repository }}:{{ .Values.client.image.tag }}"
          imagePullPolicy: {{ .Values.client.image.pullPolicy }}
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "50m"
              memory: "50Mi"
          ports:
            - containerPort: {{ .Values.client.service.targetPort }}
          env:
            - name: VITE_TICKET_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: TICKET_API_URL
            - name: VITE_USER_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: USER_API_URL
            - name: VITE_MEDIA_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: MEDIA_API_URL
            - name: VITE_AUTH_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: AUTH_API_URL
            - name: VITE_GENAI_API_URL
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: GENAI_API_URL
