apiVersion: v1
kind: Service
metadata:
  name: database-service
  namespace: "{{ .Values.prefix }}-devops25"
spec:
  selector:
    app: spoved-database-selector
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP