apiVersion: apps/v1
kind: Deployment
metadata:
  name: database
  namespace: {{ .Values.namespace.name | default "spoved" }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spoved-database-selector
  template:
    metadata:
      labels:
        app: spoved-database-selector
    spec:
      containers:
        - name: postgres
          image: "{{ .Values.database.image.repository }}:{{ .Values.database.image.tag }}"
          imagePullPolicy: {{ .Values.database.image.pullPolicy }}
          resources:
            limits:
              cpu: {{ .Values.database.resources.limits.cpu }}
              memory: {{ .Values.database.resources.limits.memory }}
            requests:
              cpu: {{ .Values.database.resources.requests.cpu }}
              memory: {{ .Values.database.resources.requests.memory }}
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-credentials
                  key: password
            - name: POSTGRES_DB
              value: "db"
          volumeMounts:
            - name: postgres-data
              mountPath: /var/lib/postgresql/data
              subPath: postgresql-db
      volumes:
        - name: postgres-data
          persistentVolumeClaim:
            claimName: postgres-pvc