apiVersion: v1
kind: Secret
metadata:
  name: gcp-credentials-secret
  namespace: {{ .Values.namespace.name | default "spoved" }}
type: Opaque
data:
  credentials.json: {{ .Values.googleCloudCredentialsJson | b64encode }} 