{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "team-spoved-ingress"
  namespace: {{ .Values.namespace.name | default "spoved" }}
  {{- $annotations := .Values.ingress.annotations | default dict }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - "team-spoved.student.k8s.aet.cit.tum.de"
      secretName: "team-spoved-devops25-tls"
  {{- end }}
  rules:
    - host: "team-spoved.devops25.student.k8s.aet.cit.tum.de"
      http:
        paths:
          # API routes for backend services
          - path: /api/v1/tickets
            pathType: Prefix
            backend:
              service:
                name: ticket-service
                port:
                  number: {{ .Values.ticket.service.port }}
          - path: /api/v1/users
            pathType: Prefix
            backend:
              service:
                name: user-service
                port:
                  number: {{ .Values.user.service.port }}
          - path: /api/v1/media
            pathType: Prefix
            backend:
              service:
                name: media-service
                port:
                  number: {{ .Values.media.service.port }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: {{ .Values.auth.service.port }}
          # Frontend route (catch-all, must be last)
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: {{ .Values.client.service.port }}
{{- end }}