{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: "spoved-ingress"
  namespace: {{ .Values.namespace.name | default "spoved" }}
  {{- $annotations := .Values.ingress.annotations | default dict }}
  {{- if $annotations }}
  annotations:
    {{- toYaml $annotations | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - "team-spoved.student.k8s.aet.cit.tum.de"
      secretName: "team-spoved-tls"
  {{- end }}
  rules:
    - host: "team-spoved.student.k8s.aet.cit.tum.de"
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: client-service
                port:
                  number: {{ .Values.client.service.port }}
{{- end }}