apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: spoved
  labels:
    app: prometheus

data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'auth'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['auth-service:8030']

      - job_name: 'media'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['media-service:8083']

      - job_name: 'user'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['user-service:8082']

      - job_name: 'ticket'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['ticket-service:8081']

      - job_name: 'genai'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['genai-service:8000']
