apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
  namespace: spoved
  labels:
    app: prometheus

data:
  prometheus.yaml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'server'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['server-service:8080']

      - job_name: 'auth'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: ['auth-service:8030']
