apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: "spoved"
type: Opaque
data:
  username: {{ .Values.database.credentials.username | b64enc }}
  password: {{ .Values.database.credentials.password | b64enc }}