apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: {{ .Values.namespace.name | default "spoved" }}
type: Opaque
data:
  username: {{ .Values.database.credentials.username | b64enc }}
  password: {{ .Values.database.credentials.password | b64enc }}