apiVersion: v1
kind: Service
metadata:
  name: server-service
  namespace: "{{ .Values.prefix }}-devops25"
spec:
  selector:
    app: spoved-server-selector
  ports:
    - port: {{ .Values.server.service.port }}
      targetPort: {{ .Values.server.service.targetPort }}
      protocol: TCP
  type: {{ .Values.server.service.type }}