apiVersion: v1
kind: ConfigMap
metadata:
  name: springboot-datalayer-config
  namespace: {{ .Values.namespace.name | default "spoved" }}
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://database-service:5432/db"
  SPRING_DATASOURCE_USERNAME: {{ .Values.dbUser }}
  SPRING_DATASOURCE_PASSWORD: {{ .Values.dbSecret }}
  SPRING_DATASOURCE_DRIVER_CLASS_NAME: "org.postgresql.Driver"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "validate"
  SPRING_JPA_PROPERTIES_HIBERNATE_DEFAULT_SCHEMA: "db"
  SPRING_JPA_SHOW_SQL: "true"
  SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: "true"
  SPRING_JPA_DATABASE_PLATFORM: "org.hibernate.dialect.PostgreSQLDialect"
