apiVersion: v1
kind: Service
metadata:
  name: ticket-service
  namespace: {{ .Values.namespace.name | default "spoved" }}
spec:
  selector:
    app: spoved-ticket-selector
  ports:
    - port: {{ .Values.ticket.service.port }}
      targetPort: {{ .Values.ticket.service.targetPort }}
      protocol: TCP
  type: {{ .Values.ticket.service.type }}
