apiVersion: apps/v1
kind: Deployment
metadata:
  name: ticket
  namespace: {{ .Values.namespace.name | default "spoved" }}
spec:
  replicas: {{ .Values.ticket.replicaCount }}
  selector:
    matchLabels:
      app: ticket-selector
  template:
    metadata:
      labels:
        app: ticket-selector
    spec:
      containers:
        - name: ticket
          image: "{{ .Values.ticket.image.repository }}:{{ .Values.ticket.image.tag }}"
          imagePullPolicy: {{ .Values.ticket.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.ticket.service.targetPort }}
          envFrom:
            - configMapRef:
                name: springboot-datalayer-config
            - configMapRef:
                name: springboot-prometheus-config
          env:
            {{- range .Values.ticket.env }}
            - name: {{ .name }}
              value: "{{ .value }}"
            {{- end }}
