apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: {{ .Values.namespace.name | default "spoved" }}
spec:
  selector:
    app: user-selector
  ports:
    - port: {{ .Values.user.service.port }}
      targetPort: {{ .Values.user.service.targetPort }}
      protocol: TCP
  type: {{ .Values.user.service.type }}
