name: Deploy to Kubernetes Cluster

on:
  workflow_call:

    # Pass KUBECONFIG as a secret
    secrets:
      KUBECONFIG:
        required: true

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Kubectl
      uses: azure/setup-kubectl@v4
      with:
        version: latest

    - name: Install Helm
      uses: azure/setup-helm@v4.3.0
      with:
        version: latest

    # Load config to .kube
    - name: Load Kubeconfig
      run: |
        mkdir -p ~/.kube
        printf "%s" "${{ secrets.KUBECONFIG }}" > ~/.kube/config

    # Run helm upgrade to upgrade deployment
    - name: Upgrade Deployment with Helm
      run: |
        helm upgrade --install meetatmensa ./helm/spoved-app -n spoved
