name: Deploy on Build Success

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    types:
      - completed

jobs:
  deploy:
    # only run if build succeeded on either dev or main
    if: >
      github.event.workflow_run.conclusion == 'success'
      && github.event.workflow_run.head_branch == 'main'
    runs-on: ubuntu-latest

    env:
      K8_USER_TOKEN: ${{ secrets.K8_USER_TOKEN }}
      GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: latest

      - name: Configure kubeconfig
        run: |
          mkdir -p ~/.kube
          cat <<EOF > ~/.kube/config
          apiVersion: v1
          kind: Config
          clusters:
          - name: student
            cluster:
              server: https://rancher.ase.cit.tum.de/k8s/clusters/c-m-nhcfjg9h
              insecure-skip-tls-verify: true
          users:
          - name: student
            user:
              token: ${K8_USER_TOKEN}
          contexts:
          - name: student
            context:
              user: student
              cluster: student
          current-context: student
          EOF

      - name: Install Helm
        uses: azure/setup-helm@v4.3.0
        with:
          version: latest

      - name: Upgrade Deployment with Helm
        run: |
          helm upgrade --install spoved-app ./helm/spoved-app \
            -n spoved-2 \
            --set geminiApiKey=${GEMINI_API_KEY} \
            --set GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
