name: Test

on:
  push:
    branches: [ dev, main ]

jobs:
  test-ticket:
    name: Run Java Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Gradle test
        working-directory: ./ticket
        run: ./gradlew test

  test-user:
    name: Run Java Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Gradle test
        working-directory: ./user
        run: ./gradlew test

  test-media:
    name: Run Java Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Gradle test
        working-directory: ./media
        run: ./gradlew test

  test-auth:
    name: Run Java Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Run Gradle test
        working-directory: ./auth
        run: ./gradlew test

  test-frontend:
    name: Run NPM Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      
      - name: Install dependencies (Client)
        working-directory: ./client/frontend
        run: npm ci

      - name: Run ESLint on changed files
        working-directory: ./client/frontend
        run: npm run lint

      - name: Run tests
        working-directory: ./client/frontend
        # FIXME Since no testing framework was used, it's currently repeating the linting
        run: npm run lint

  test-genai:
    name: Run Python Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with: 
          python-version: 3.9

      - name: Install dependencies (GenAI)
        working-directory: ./genai
        run: pip install -r requirements.txt